### ISSUE TITLE
About GPU memory usage

### ISSUE THREAD

**Issue by bupticybee** [shacklettbp/madrona#37] opened 2024-08-21 05:56 UTC
Thanks for this amazing work. Really like this.

I find in your examples that no matter what number of num-envs I set, GPU memory usage is similar. So I guess not that much GPU memory might be needed after all. Is there some option or ways to reduce GPU memory requirement?

Thanks in advance.

**Comment by shacklettbp** [comment] 2024-08-21 06:39
In general there are some aspects of Madrona that are not super optimized for memory usage currently.

I'll need more specifics to answer your questions. What commands are you running? What memory usage are you seeing, etc?

**Comment by bupticybee** [comment] 2024-08-21 06:55
Testing with https://github.com/bsarkar321/madrona_rl_envs/tree/main/src/hanabi_env#hanabi-environment

I'm working on a machine with 1xV100 GPU.

When I run command :

```
(madrona) icybee666@gpu-env-dev:~/projects/gitprojects/madrona_rl_envs/scripts$ MADRONA_MWGPU_KERNEL_CACHE=/tmp/hanabi python hanabi_example.py --num-envs 10000
Using 256 1 80 as the default megakernel configuration
Initialization finished
Running Simulation: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:04<00:00, 203.15it/s]
step * worlds / sec: 5964395.961682742
(madrona) icybee666@gpu-env-dev:~/projects/gitprojects/madrona_rl_envs/scripts$ 
``` 

So when using 10k env, throughput at ~6 million frame/s. Takes about 14Gb gpu memory when running.

<img width="702" alt="2024-08-21 14 50 09" src="https://github.com/user-attachments/assets/be0a8993-c03a-42be-8a99-ccb0c4c60c80">


When running with 10 env:

```
(madrona) icybee666@gpu-env-dev:~/projects/gitprojects/madrona_rl_envs/scripts$ MADRONA_MWGPU_KERNEL_CACHE=/tmp/hanabi python hanabi_example.py --num-envs 10
Using 256 1 80 as the default megakernel configuration
Initialization finished
Running Simulation: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:00<00:00, 1085.47it/s]
step * worlds / sec: 17435.75758986621
(madrona) icybee666@gpu-env-dev:~/projects/gitprojects/madrona_rl_envs/scripts$ 
```

throughput indicates GPU usage is a lot smaller.

But when checking gpu usage when it's running:

<img width="698" alt="2024-08-21 14 53 26" src="https://github.com/user-attachments/assets/103b94bd-e312-4704-b474-0f7ebfb6f9d4">

Takes almost as much gpu memory.

It would be good to keep some portion of memory so the those part can be used for training or rollour worker inferencing.

**Comment by shacklettbp** [comment] 2024-08-21 16:05
I'm not sure why the Hanabi environment is using that much memory. Madrona doesn't reserve all GPU memory or anything like that, it just uses what it needs (+ a little bit of extra waste).

I'll ping the author of the Hanabi environment to see if he can shed some light on what's going on here.

**Comment by bupticybee** [comment] 2024-08-22 02:15
> I'm not sure why the Hanabi environment is using that much memory. Madrona doesn't reserve all GPU memory or anything like that, it just uses what it needs (+ a little bit of extra waste).
> 
> I'll ping the author of the Hanabi environment to see if he can shed some light on what's going on here.

Thanks. I'll check other env for memory usage.

**Comment by bupticybee** [comment] 2024-08-22 06:36
I don't think it's a hanabi env problem. I'm also trying with cartpole env. It also take most of GPU memory no matter how many env I use.


 python cartpole_example.py --num-envs 32 --num-steps 10000000

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100-SXM2-16GB           On  |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P0             45W /  300W |   13952MiB /  16384MiB |     34%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                     

python cartpole_example.py --num-envs 10 --num-steps 10000000

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100-SXM2-16GB           On  |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P0             42W /  300W |   13952MiB /  16384MiB |     34%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

python cartpole_example.py --num-envs 1 --num-steps 10000000

Thu Aug 22 06:32:53 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100-SXM2-16GB           On  |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P0             41W /  300W |   13952MiB /  16384MiB |     32%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

**Comment by bupticybee** [comment] 2024-08-22 06:38
I don't think it's a hanabi env problem. I'm also trying with cartpole env. It also take most of GPU memory no matter how many env I use.


<img width="568" alt="2024-08-22 14 36 57" src="https://github.com/user-attachments/assets/a1275f54-ceed-4b27-8ae4-f23fdd1c27f9">

**Comment by shacklettbp** [comment] 2024-08-22 18:40
Can you try the madrona_escape_room environment?

**Comment by bupticybee** [comment] 2024-08-23 07:08
> Can you try the madrona_escape_room environment?

Also has the problem but memory usage is lower at 7Gb.

10 env:

<img width="996" alt="2024-08-23 15 03 00" src="https://github.com/user-attachments/assets/c687a1ec-6e28-4681-8ba0-61e1e01867bb">

100 env:

<img width="1054" alt="2024-08-23 15 01 22" src="https://github.com/user-attachments/assets/f907f881-1ab2-4bc5-9384-3e38db6ac8e2">

1000 env:

<img width="1046" alt="2024-08-23 15 06 18" src="https://github.com/user-attachments/assets/0f026d13-9747-45d7-931b-4f04f8bddb79">

**Comment by bupticybee** [comment] 2024-08-23 07:09
> > Can you try the madrona_escape_room environment?
> 
> Also has the problem but memory usage is lower at 7Gb.
> 
> 10 env:
> 
> <img alt="2024-08-23 15 03 00" width="996" src="https://private-user-images.githubusercontent.com/9393610/360824059-c687a1ec-6e28-4681-8ba0-61e1e01867bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTcyMDgsIm5iZiI6MTcyNDM5NjkwOCwicGF0aCI6Ii85MzkzNjEwLzM2MDgyNDA1OS1jNjg3YTFlYy02ZTI4LTQ2ODEtOGJhMC02MWUxZTAxODY3YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDcwODI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTBkNDc5YzM2OTUxNGVjY2Y0NDFmNzJkZTljN2FiY2ZiZGY4NTUxZDA0YTNhODY2M2FkYjg1N2UwMjg0MGQ1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IlMMIwMUzGXkmIKuNmvEVRcxr3BP3gY5wXDxDjssEnM">
> 100 env:
> 
> <img alt="2024-08-23 15 01 22" width="1054" src="https://private-user-images.githubusercontent.com/9393610/360825047-f907f881-1ab2-4bc5-9384-3e38db6ac8e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTcyMDgsIm5iZiI6MTcyNDM5NjkwOCwicGF0aCI6Ii85MzkzNjEwLzM2MDgyNTA0Ny1mOTA3Zjg4MS0xYWIyLTRiYzUtOTM4NC0zZTM4ZGI2YWM4ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDcwODI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzU0YTMxMGFiOTE1NzRjMDI2NGI3MjUxMGE3MTA5MTVjOTY0ODEyOTg0ZjQ1OGZhYzFmNDZiOWZhNGQ2Y2UwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iFLpApEModPnecuwUheOjp8f1_o3AdO-Vnvz4laSK2A">
> 1000 env:
> 
> <img alt="2024-08-23 15 06 18" width="1046" src="https://private-user-images.githubusercontent.com/9393610/360825126-0f026d13-9747-45d7-931b-4f04f8bddb79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTcyMDgsIm5iZiI6MTcyNDM5NjkwOCwicGF0aCI6Ii85MzkzNjEwLzM2MDgyNTEyNi0wZjAyNmQxMy05NzQ3LTQ1ZDctOTMxYi00ZjA0ZjhiZGRiNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDcwODI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjk1NDYzNDI0ZjFkMGNkYjBkMjcxMmI4NjMwN2MyZDkwYzRmZTk2Y2M4ZjU3NTQyZDk0NzUxMTZhODVhNzc3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zklbtoGnnutWdCws_RTJTHUPCdM-CURXT1iV0hPM5eQ">

It's kind of wired since to me escape room is way more complicated game than the other two.

**Comment by shacklettbp** [comment] 2024-10-10 05:09
I finally had a chance to look into this. I can reproduce the roughly ~7GB base memory usage, although memory usage *does* go up as the number of worlds increases. For example 16384 worlds takes ~12GB of ram. The main issues here are that madrona allocates a fixed size memory pool (4GB) for one-off allocations, each GPU thread has a bit of temporary scratch space that adds up on on large GPUs, and finally, each ECS archetype has a default initial table size that may be wasting a significant amount of memory. I'm a bit concerned about breaking existing environments by reducing the fixed size memory pool size below 4GB, although there is an environment variable MADRONA_MWGPU_DEVICE_HEAP_SIZE (in bytes) that you can use to reduce the pool size.

The ideal solution would be a more robust memory management solution that gets rid of this fixed size pool and perhaps reduces the initial ECS table sizes, but this is unlikely to happen before a larger overhaul of the ECS memory management, unless an external contributor wants to address this.

If this is blocking your use case for Madrona let me know (reopen this issue) and we can come up with a a workaround or other solution, but for now I'm going to close this issue as I don't think there is an immediate action item. 

P.S. The worse memory usage in the madrona_rl_envs repo is probably due to older versions of Madrona using an even larger fixed size pool. The original author of those repos has graduated, so I can't promise any fixes there. I would recommend opening an issue asking if Madrona can be updated in those repos.

**Closed by shacklettbp** 2024-10-10 05:09 UTC
